version: '3.8'
services:
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp

  # ✅ Thêm Redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - freecodecamp
    restart: unless-stopped

networks:
  freecodecamp:

volumes:
  redis_data: